### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/<USER>/.steam/steam/steamapps/common/Proton 5.0/dist/bin

### ISSUE THREAD

**Issue by ghost** [Linux74656/SpaceEngineersLinuxPatches#30]
```~ >>> protontricks 244850 --force -q dotnet472 vcrun2015 faudio d3dcompiler_47
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 11, in <module>
    load_entry_point('protontricks==1.4.1', 'console_scripts', 'protontricks')()
  File "/usr/lib/python3.8/site-packages/protontricks/cli.py", line 248, in main
    run_command(
  File "/usr/lib/python3.8/site-packages/protontricks/util.py", line 154, in run_command
    wine_bin_dir = create_wine_bin_dir(proton_app=proton_app)
  File "/usr/lib/python3.8/site-packages/protontricks/util.py", line 46, in create_wine_bin_dir
    binaries = list((
  File "/usr/lib/python3.8/pathlib.py", line 1113, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/home/<USER>/.steam/steam/steamapps/common/Proton 5.0/dist/bin'

```
Steam doesn't decompress proton_dist.tar when proton 5.0 is downloaded, requires user to decompress the contents of the archive to a new folder in the proton 5.0 directory called dist. Easy fix, but no documentation on this repository.

**Comment by Linux74656** [comment]
This is a Proton specific issue, well outside of the scope of this repo. This would easily affect games other than Space Engineers, you should open this issue https://github.com/ValveSoftware/Proton/issues if it does not already exist, that way people who have this problem outside of SE can find this solution.
