### ISSUE TITLE
Add "Too many open files" and its solution to the known issues list

### ISSUE THREAD

**Issue by CrushedPixl** [Linux74656/SpaceEngineersLinuxPatches#35]
I am running Artix Linux with OpenRC, and by default it comes with these ulimit limits for the max number of open file descriptors:
```
$ ulimit -Hn # Hard limit
4096
$ ulimit -Sn # Soft limit
1024
```

This resulted in a crash whenever loading a save with the following log message (in MYSTEAMPATH/steamapps/compatdata/244850/pfx/drive_c/users/steamuser/Application Data/SpaceEngineers/SpaceEngineers_DATEANDTIME.log):
```
2020-06-28 01:17:33.540 - Thread:   1 ->     Saving Sandbox world configuration file C:\users\steamuser\Application Data\SpaceEngineers\Saves\76561198189349211\The First Jump 2020-06-28 01-17-24\Mission 01\.new\Sandbox_config.sbc
2020-06-28 01:17:33.558 - Thread:   1 ->  Session snapshot save - END
2020-06-28 01:17:33.558 - Thread:   1 ->  RunLoadingAction - END
2020-06-28 01:17:33.559 - Thread:   1 ->  MyGuiScreenGamePlay.LoadData - START
2020-06-28 01:17:33.702 - Thread:   1 ->  MyGuiScreenGamePlay.LoadData - END
2020-06-28 01:17:33.702 - Thread:   1 ->  MyGuiScreenGamePlay.LoadContent - START
2020-06-28 01:17:33.702 - Thread:   1 ->  MyGuiScreenGamePlay.LoadContent - END
2020-06-28 01:17:33.715 - Thread:   1 ->  Updating continues.
2020-06-28 01:17:33.733 - Thread:   1 ->  Exception occured: System.IO.IOException: Too many open files.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.Threading.Semaphore..ctor(Int32 initialCount, Int32 maximumCount, String name)
   at VRage.FastResourceLock..ctor()
   at Sandbox.Game.World.Generator.MyProceduralCell..ctor(Vector3I cellId, Double cellSize)
   at Sandbox.Game.World.Generator.MyStationCellGenerator.GenerateProceduralCell(Vector3I& cellId)
   at Sandbox.Game.World.Generator.MyProceduralWorldModule.GenerateObjectSeeds(BoundingSphereD& sphere)
   at Sandbox.Game.World.Generator.MyProceduralWorldGenerator.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2020-06-28 01:17:33.734 - Thread:   1 ->  Showing message
2020-06-28 01:17:33.738 - Thread:   1 ->  Log Closed
```

My solution was to increase the ulimit for `nofile` in `/etc/security/limits.conf` by appending the following lines:
```
*	soft	nofile	16384
*	hard	nofile	32768
```
... which after applied through a reboot increased the limit:
```
$ ulimit -Hn # Hard limit
32768
$ ulimit -Sn # Soft limit
16384
```
... and solved my problem.

My guess is that this is OpenRC specific, as it didn't occur when I played SE on Arch with systemd.

**Comment by Linux74656** [comment]
This is already known for the basic proton setup. Here: https://github.com/ValveSoftware/Proton/wiki/Requirements#fd-limit-requirements-systemd--240

It specifically states 
> If you're not running Ubuntu, SteamOS or Debian, please follow the instructions over at https://github.com/zfigura/wine/blob/esync/README.esync to increase your FD limit.

Since it won't hurt... I will go ahead and add "Ensure proton is properly installed and setup" to the guide setup.

EDIT: I should really read more carefully. I noticed you only had this issue with openRC. I will make a special note of this in the readme. Sorry for the confusion!
