### ISSUE TITLE
Exception running PatcherGUI.jar

### ISSUE THREAD

**Issue by ghost** [Linux74656/SpaceEngineersLinuxPatches#42]
I am getting the below error when running `java -jar PatcherGUI.jar`
Arch
jre8-openjdk 8.u265-1
jre8-openjdk-headless 8.u265-1
jre-openjdk-headless 14.0.2.u12-1

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-14-openjdk/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2640)
	at java.base/java.lang.Runtime.load0(Runtime.java:745)
	at java.base/java.lang.System.load(System.java:1871)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2658)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:807)
	at java.base/java.lang.System.loadLibrary(System.java:1907)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1380)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1378)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1377)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1410)
	at java.desktop/java.awt.Font.<clinit>(Font.java:260)
	at PatchGUI.main(PatchGUI.java:135)
```

**Comment by Linux74656** [comment]
It looks like the patcher is trying to use java-14-openjdk, here: /usr/lib/jvm/java-14-openjdk/... but can not find it.

Currently jre-openjdk-headless 14.0.2.u12-1 is installed, and headless generally does not have any graphics packages, like AWT/SWING.

Since you already have java 8 openjdk installed, you can point to a specific java version by running:
/usr/lib/jvm/java-8-openjdk/bin/java -jar PatcherGUI.jar
*NOTE: You may have to adjust the path above to fit your actual location of Java 8 JDK, it may be something slightly different with a -amd64 at the end or such...*

OR
You can install the full openjdk14(which should include the headless package, or can be installed alongside if needed) and use java14... however I do not know if you have specific reasons to use various java versions other than the ones you have installed, as java8 will work with the patcher.

**Comment by ghost** [comment]
I just went by the latest release on java.com, but installed it through the AUR. Havent messed with Java in a while, so not sure why theres a v8, and the next version is v14.

I will try this out and close if it fixes my issue.

**Comment by ghost** [comment]
That worked. Java 8, but I seem to be stuck at 

```
Using native override for following DLLs: xapofx1_1
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
```

No errors, nothing in terminal, just stuck there for the past 15 minutes.

**Comment by Linux74656** [comment]
This is certainly dotnet frameworks stalling. You can try to manually install dotnet48 into your prefix.

Something like:
`WINEPREFIX=/home/USERNAME/.steam/steam/steamapps/compatdata/244850/pfx/ winetricks --force -q dotnet48`
*NOTE: Your prefix maybe located in another location depending on where you installed the game.*

**Comment by ghost** [comment]
Done that. I can get to the point where I load into a new game (or save game, although I deleted all of those) and then my computer pretty much dies. What I mean is I get a TON of artifacting on one or both monitors right as the game should have finished loading.

Either way, seems to only happen on some of the preset loads for new games and not all. Not sure what the deal is.

Thanks for the help!
