### ISSUE TITLE
Last Update Error [patch is broken now]

### ISSUE THREAD

**Issue by MAGGen-hub** [Linux74656/SpaceEngineersLinuxPatches#59]
For some reason I got this every time I tried to enter the game(
Also the game started to work without any .NET framework but mods and skripts... They brokend I think(
My libs:
.NET Framework 4.8
xact64
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at VRage.Platform.Windows.Forms.MyMessageBoxCrashForm.linklblLog_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SpaceEngineers
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/SpaceEngineers.exe
----------------------------------------
VRage
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
SpaceEngineers.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/SpaceEngineers.Game.DLL
----------------------------------------
Sandbox.Game
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/Sandbox.Game.DLL
----------------------------------------
VRage.Library
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
VRage.Math
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Math.DLL
----------------------------------------
VRage.Render
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Render.DLL
----------------------------------------
VRage.Game
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Game.DLL
----------------------------------------
Sandbox.Graphics
    Assembly Version: 0.1.1.0
    Win32 Version: 0.1.1
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/Sandbox.Graphics.DLL
----------------------------------------
VRage.Input
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Input.DLL
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/System.Collections.Immutable.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
VRage.Platform.Windows
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Platform.Windows.DLL
----------------------------------------
VRage.Steam
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Steam.DLL
----------------------------------------
VRage.EOS
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.EOS.DLL
----------------------------------------
EOSSDK
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/EOSSDK.DLL
----------------------------------------
VRage.Mod.Io
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Mod.Io.DLL
----------------------------------------
VRage.Render11
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Render11.DLL
----------------------------------------
Steamworks.NET
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/Steamworks.NET.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
VRage.Scripting
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/VRage.Scripting.DLL
----------------------------------------
SharpDX.DXGI
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/SharpDX.DXGI.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
SharpDX
    Assembly Version: 4.2.0.0
    Win32 Version: 4.2.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/SharpDX.DLL
----------------------------------------
RestSharp
    Assembly Version: 106.6.10.0
    Win32 Version: 106.6.10.0
    CodeBase: file:///Z:/home/maggen/.local/share/Steam/steamapps/common/SpaceEngineers/Bin64/RestSharp.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by MAGGen-hub** [comment]
Some new info: if you try game just with the dotnet48 47 the game will start to freze even on main menu and then can FREEZE the entire OS. With dotnet < 47 game simply not working (can't even see the logo).

**Comment by MAGGen-hub** [comment]
I tryed different solutions from this guid but nothing helped.

**Comment by arch-user-france1** [comment]
It should work
