### ISSUE TITLE
Patch is broken

### ISSUE THREAD

**Issue by droslean** [Linux74656/SpaceEngineersLinuxPatches#60]
```
lutris-wrapper: /usr/bin/bash
Started initial process 15185 from /usr/bin/bash -c java -jar /home/droslean/.cache/lutris/installer/space-engineers/PatcherGUI/PatcherGUI.jar
Start monitoring process.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc34.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/java.awt.Font.<clinit>(Font.java:260)
	at PatchGUI.main(PatchGUI.java:135)
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256

```

I can assume that my java version can be a problem. Can anyone let us know the correct java version?

**Comment by ichbestimmtnicht** [comment]
just ran it with openjdk 17 - worked so far
![image](https://user-images.githubusercontent.com/28549503/168886137-223c295a-1ffa-4a00-95f0-25b154674099.png)
